### ISSUE TITLE
File upload expects file to be in a specific folder

### ISSUE THREAD

**Issue by dtanman** [nicolecvaldez/campaign-measurement-webapp#1]
晚上好！我发现到的问题是。。。

Just kidding.

When I uploaded a file from a different folder in my computer (say, `abc.csv`, for example), I get the following error:

`IOError: [Errno 2] No such file or directory: '/Users/nicole/git/campaign-measurement-webapp/app/uploads/abc.csv'`

Is this expected? It seems to look for the upload within that folder.

(Also, I wanted to try submitting an issue!)

**Comment by nicolecvaldez** [comment]
Helloooo andre. Can I see the structure of your directory?

First thing I can think of is that it needs a folder named "upload" because it saves the csv there after upload. I cant push an empty folder in github so this folder is missing. And this problem (i think) can be solved if we deploy using docker, im not entirely sure.
